const ProductData = [
    {
        "id": 1,
        "title": "Traditional Embroidered Kurti with Palazzo Set",
        "description": "Add elegance to your wardrobe with this beautifully embroidered kurti and palazzo set. Made from high-quality pure cotton, it offers both comfort and style. Perfect for festive occasions or casual gatherings.",
        "prevPrice": 870,
        "price": 618,
        "discountPercentage": 12.96,
        "review": 44987,
        "rating": 4.6,
        "stock": 94,
        "brand": "Zara",
        "category": "women-ethnic",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/xif0q/kurta/k/9/m/m-y1001-klosia-original-imagmsx5thbg8bgj.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/kurta/k/9/m/m-y1001-klosia-original-imagmsx5thbg8bgj.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/kurta/t/y/r/m-y1001-klosia-original-imagmsx5sjsbcxzn.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/kurta/r/y/k/m-y1001-klosia-original-imagmsx5fjb7ebfs.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/kurta/6/x/h/m-y1001-klosia-original-imagmsx5bznjzpgx.jpeg?q=70",

        ]
    },
    {
        "id": 2,
        "title": "Elegant Silk Saree with Zari Border",
        "description": "Step into the world of grace and charm with this exquisite silk saree. The zari border adds a touch of opulence, making it perfect for weddings and special occasions. Embrace tradition with this timeless ensemble.",
        "prevPrice": 1199,
        "price": 899,
        "discountPercentage": 17.94,
        "review": 4987,
        "rating": 4.0,
        "stock": 34,
        "brand": "Puma",
        "category": "women-ethnic",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/l3t2fm80/ethnic-set/u/2/1/l-jk173-jai-kurties-original-imageugcbqk36gvg.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/l3t2fm80/ethnic-set/u/2/1/l-jk173-jai-kurties-original-imageugcbqk36gvg.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l3t2fm80/ethnic-set/9/a/a/l-jk173-jai-kurties-original-imageugcj6kzrqgm.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l3t2fm80/ethnic-set/9/a/a/l-jk173-jai-kurties-original-imageugcj6kzrqgm.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l3t2fm80/ethnic-set/y/o/s/l-jk173-jai-kurties-original-imageugcfvgahxpp.jpeg?q=70"
        ]
    },
    {
        "id": 3,
        "title": "Stylish Embroidered Anarkali Suit",
        "description": "Dazzle everyone with this stunning embroidered Anarkali suit. The intricate work and flowing silhouette make it a perfect choice for special occasions and celebrations. Embrace elegance and make a lasting impression.",
        "prevPrice": 1599,
        "price": 1249,
        "discountPercentage": 15.46,
        "review": 14987,
        "rating": 4.9,
        "stock": 36,
        "brand": "Adidas",
        "category": "women-ethnic",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/a/o/8/m-krpl00144-githaan-original-imagghjutbhw9g3z.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/a/o/8/m-krpl00144-githaan-original-imagghjutbhw9g3z.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/m/u/q/m-krpl00144-githaan-original-imagghjuvepyjqgy.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/f/c/h/m-krpl00144-githaan-original-imagghjux9xqjgyj.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/l/m/a/m-krpl00144-githaan-original-imagghjuzzfv2ycz.jpeg?q=70",
        ]
    },
    {
        "id": 4,
        "title": "Graceful Ethnic Kurta with Palazzo Set",
        "description": "Stay comfortable and stylish with this graceful ethnic kurta and palazzo set. The intricate detailing and pure cotton fabric make it a perfect choice for casual outings or festive gatherings. Elevate your ethnic wardrobe with this timeless ensemble.",
        "prevPrice": 470,
        "price": 280,
        "discountPercentage": 17.91,
        "review": 9867,
        "rating": 4.3,
        "stock": 123,
        "brand": "Zara",
        "category": "women-ethnic",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/l0sgyvk0/ethnic-set/f/6/p/m-cf1423black-charu-original-imagchu7kgythszg.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/l0sgyvk0/ethnic-set/f/6/p/m-cf1423black-charu-original-imagchu7kgythszg.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l0sgyvk0/ethnic-set/u/h/7/m-cf1423black-charu-original-imagchu7vkrmgj9x.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l0sgyvk0/ethnic-set/m/v/p/m-cf1423black-charu-original-imagchu7jkyvvpsy.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l0sgyvk0/ethnic-set/m/8/k/m-cf1423black-charu-original-imagchu7hw7eypyj.jpeg?q=70",

        ]
    },
    {
        "id": 5,
        "title": "Traditional Handloom Silk Saree",
        "description": "Wrap yourself in elegance with this traditional handloom silk saree. The exquisite craftsmanship and rich texture make it a perfect choice for weddings and festive occasions. Embrace the timeless beauty of Indian heritage.",
        "prevPrice": 670,
        "price": 499,
        "discountPercentage": 10.58,
        "review": 872,
        "rating": 4.1,
        "stock": 32,
        "brand": "Puma",
        "category": "women-ethnic",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/m/h/3/m-vv-9180-vredevogel-original-imagh4qrkuduwrgj.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/m/h/3/m-vv-9180-vredevogel-original-imagh4qrkuduwrgj.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/f/e/0/m-vv-9180-vredevogel-original-imagh4qrwc7kzfcb.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/m/a/c/m-vv-9180-vredevogel-original-imagh4qrsaqva6df.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/h/l/s/m-vv-9180-vredevogel-original-imagh4qrywjvkq4j.jpeg?q=70"
        ]
    },
    {
        "id": 6,
        "title": "Elegant Embroidered Lehenga Choli",
        "description": "Make a statement with this elegant embroidered lehenga choli. The intricate work and beautiful design exude grace and charm. Perfect for weddings and festivities, it will make you the center of attention.",
        "prevPrice": 1999,
        "price": 1749,
        "discountPercentage": 11.02,
        "review": 34562,
        "rating": 4.5,
        "stock": 83,
        "brand": "Zara",
        "category": "women-ethnic",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/kkbh8cw0/ethnic-set/v/r/a/m-991green-vastranikhar-original-imafzzs92fvyx6fy.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/kkbh8cw0/ethnic-set/v/r/a/m-991green-vastranikhar-original-imafzzs92fvyx6fy.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/kkbh8cw0/ethnic-set/6/e/y/m-991green-vastranikhar-original-imafzzs9wahukxv9.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/kkbh8cw0/ethnic-set/p/e/a/m-991green-vastranikhar-original-imafzzs9sev5ghmh.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/kkbh8cw0/ethnic-set/p/p/b/m-991green-vastranikhar-original-imafzzs9rhyzu9fx.jpeg?q=70"
        ]
    },
    {
        "id": 7,
        "title": "Traditional Bandhani Print Saree",
        "description": "Add a touch of vibrant elegance to your wardrobe with this traditional bandhani print saree. The intricate patterns and rich colors make it a perfect choice for traditional occasions and celebrations.",
        "prevPrice": 1799,
        "price": 1499,
        "discountPercentage": 4.15,
        "review": 12432,
        "rating": 4.2,
        "stock": 50,
        "brand": "Adidas",
        "category": "women-ethnic",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/4/3/e/s-58-loopsacreation-original-imagmgy28cutapwd.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/4/3/e/s-58-loopsacreation-original-imagmgy28cutapwd.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/l/f/g/s-58-loopsacreation-original-imagmgy27yc34ram.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/d/7/g/s-58-loopsacreation-original-imagmgy2vmusyxku.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/z/w/t/s-58-loopsacreation-original-imagmgy2apv7pr6r.jpeg?q=70"
        ]
    },
    {
        "id": 8,
        "title": "Women Cotton Anarkali Suit Set",
        "description": "Step into grace and elegance with this beautiful cotton anarkali suit set. The intricate embroidery and flowing silhouette create a stunning ensemble for special occasions and festivities.",
        "prevPrice": 1870,
        "price": 1499,
        "discountPercentage": 10.23,
        "review": 98122,
        "rating": 4.3,
        "stock": 68,
        "brand": "Puma",
        "category": "women-ethnic",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/xif0q/kurta/r/0/o/m-9954-krisjan-original-imaghxrwkdjdr7ds.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/kurta/r/0/o/m-9954-krisjan-original-imaghxrwkdjdr7ds.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/kurta/2/i/e/m-9954-krisjan-original-imaghxrwkxy2g3ar.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/kurta/u/t/z/m-9954-krisjan-original-imaghxrwfxbekuvr.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/kurta/v/h/2/m-9954-krisjan-original-imaghxrwn5gzzu5j.jpeg?q=70",

        ]
    },
    {
        "id": 9,
        "title": "Women Designer Ethnic Kurti",
        "description": "Get ready to make a style statement with this designer ethnic kurti. The exquisite design and comfortable fabric make it a perfect choice for both casual and festive occasions. Embrace the fusion of tradition and modernity.",
        "prevPrice": 1299,
        "price": 1069,
        "discountPercentage": 11.83,
        "review": 1112,
        "rating": 4.4,
        "stock": 96,
        "brand": "Zara",
        "category": "women-ethnic",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/l19m93k0/ethnic-set/2/9/y/xxl-vv-9206-vredevogel-original-imagcv45njsggbdz.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/l19m93k0/ethnic-set/c/i/3/xxl-vv-9206-vredevogel-original-imagcv45g5dmuzrd.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l19m93k0/ethnic-set/d/h/n/xxl-vv-9206-vredevogel-original-imagcv45htyvzzmh.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l19m93k0/ethnic-set/d/h/n/xxl-vv-9206-vredevogel-original-imagcv45htyvzzmh.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l19m93k0/ethnic-set/8/g/t/xxl-vv-9206-vredevogel-original-imagcv45fwcz7kgu.jpeg?q=70",
        ]
    },
    {
        "id": 10,
        "title": "Women Embroidered Banarasi Saree",
        "description": "Experience the timeless beauty of Banarasi craftsmanship with this embroidered Banarasi saree. The intricate patterns and luxurious fabric make it a perfect choice for weddings and special occasions. Embrace the grandeur of Indian traditions.",
        "prevPrice": 1270,
        "price": 1099,
        "discountPercentage": 6.18,
        "review": 8977,
        "rating": 4.3,
        "stock": 89,
        "brand": "Adidas",
        "category": "women-ethnic",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/ktketu80/salwar-kurta-dupatta/n/b/8/3xl-vfku1103skd-vbuyz-original-imag6vzvgpq2azkf.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/ktketu80/salwar-kurta-dupatta/n/b/8/3xl-vfku1103skd-vbuyz-original-imag6vzvgpq2azkf.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/ktketu80/salwar-kurta-dupatta/y/1/7/3xl-vfku1103skd-vbuyz-original-imag6vzv8wnfqf3h.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/ktketu80/salwar-kurta-dupatta/l/3/o/3xl-vfku1103skd-vbuyz-original-imag6vzvnzyhgz6u.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/ktketu80/salwar-kurta-dupatta/a/b/c/3xl-vfku1103skd-vbuyz-original-imag6vzvqz3qwnfj.jpeg?q=70",
        ]
    },
    {
        "id": 11,
        "title": "Women Floral Print Maxi Dress",
        "description": "Get ready for a stylish summer with this elegant Floral Print Maxi Dress. Perfect for any occasion, this dress features a vibrant floral pattern that will make you stand out from the crowd. Made with high-quality materials, it offers comfort and style in one package. Embrace your inner fashionista and make a statement with this stunning dress.",
        "prevPrice": 1269,
        "price": 913,
        "discountPercentage": 8.4,
        "review": 5664,
        "rating": 4.2,
        "stock": 65,
        "brand": "Zara",
        "category": "women-western",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/k/a/i/s-dd525-dresss-deklook-original-imagjxz4kmv5snaz.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/k/a/i/s-dd525-dresss-deklook-original-imagjxz4kmv5snaz.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/4/z/x/s-dd525-dresss-deklook-original-imagjxz4jgsggyc3.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/u/z/t/s-dd525-dresss-deklook-original-imagjxz4sttdz6p7.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/o/n/t/s-dd525-dresss-deklook-original-imagjxz4zegwhzjy.jpeg?q=70",
        ]
    },

    {
        "id": 12,
        "title": "Women Denim Jacket with Embroidery Detail",
        "description": "Add a touch of style to your wardrobe with this trendy Denim Jacket. The jacket features intricate embroidery detailing that adds a unique and fashionable flair. Made with high-quality denim, it offers durability and comfort. Whether you're going for a casual look or want to dress up, this jacket is the perfect choice for any occasion.",
        "prevPrice": 999,
        "price": 894,
        "discountPercentage": 15.66,
        "review": 11243,
        "rating": 4,
        "stock": 52,
        "brand": "Gucci",
        "category": "women-western",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/xif0q/t-shirt/1/d/2/s-3813-the-dry-state-original-imagcfh833gdjeem-bb.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/t-shirt/1/d/2/s-3813-the-dry-state-original-imagcfh833gdjeem-bb.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l071d3k0/t-shirt/8/r/l/xl-3813-the-dry-state-original-imagcfh8kyzzuwm2.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l071d3k0/t-shirt/j/j/n/xl-3813-the-dry-state-original-imagcfh8vtjfhfgc.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l071d3k0/t-shirt/p/m/y/s-3813-the-dry-state-original-imagcfh8bxr5qagu.jpeg?q=70",
        ]
    },

    {
        "id": 13,
        "title": "Women Off-Shoulder Ruffle Top",
        "description": "Make a fashion statement with this stunning Off-Shoulder Ruffle Top. The off-shoulder design and ruffle detailing give it a chic and feminine look that is perfect for any occasion. Made with high-quality fabric, it offers comfort and style in one package. Pair it with your favorite jeans or skirt for a stylish and trendy ensemble.",
        "prevPrice": 1870,
        "price": 1399,
        "discountPercentage": 8.14,
        "review": 1231,
        "rating": 4.5,
        "stock": 61,
        "brand": "Zara",
        "category": "women-western",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/km9ht3k0/top/w/h/p/xl-tttp004055-tokyo-talkies-original-imagf7eguxbuf6y5.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/km9ht3k0/top/w/h/p/xl-tttp004055-tokyo-talkies-original-imagf7eguxbuf6y5.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/km9ht3k0/top/k/a/t/xl-tttp004055-tokyo-talkies-original-imagf7egq4fngrrk.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/kmmcrrk0/night-dress-nighty/v/c/m/m-ttth000008-tokyo-talkies-original-imagfh86jgnzunyy.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/km9ht3k0/top/y/r/q/xl-tttp004055-tokyo-talkies-original-imagf7egh6y3a6ga.jpeg?q=70",
        ]
    },

    {
        "id": 14,
        "title": "Women Striped Wrap Skirt",
        "description": "Add a touch of elegance to your wardrobe with this beautiful Striped Wrap Skirt. The striped pattern and wrap design give it a sophisticated and stylish look. Made with high-quality materials, it offers comfort and durability. Whether you're going to a party or a casual outing, this skirt is the perfect choice for a fashionable and trendy outfit.",
        "prevPrice": 1470,
        "price": 1200,
        "discountPercentage": 15.6,
        "review": 33342,
        "rating": 4.21,
        "stock": 114,
        "brand": "Gucci",
        "category": "women-western",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/l3lx8cw0/dress/z/a/h/s-337tk10083-selvia-original-imagepfwavcst5jh.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/l3lx8cw0/dress/z/a/h/s-337tk10083-selvia-original-imagepfwavcst5jh.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l3lx8cw0/dress/v/y/z/s-337tk10083-selvia-original-imagepfwazbt8bwu.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l3lx8cw0/dress/u/v/j/s-337tk10083-selvia-original-imagepfwcdw4s3cc.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l3lx8cw0/dress/y/w/o/s-337tk10083-selvia-original-imagepfwwkzysjtf.jpeg?q=70"
        ]
    },

    {
        "id": 15,
        "title": "Women Graphic Print T-Shirt Dress",
        "description": "Stay trendy and comfortable with this stylish Graphic Print T-Shirt Dress. The dress features a unique and eye-catching graphic print that adds a fashionable touch to your look. Made with soft and breathable fabric, it offers all-day comfort. Whether you're going for a casual outing or hanging out with friends, this dress is a must-have in your wardrobe.",
        "prevPrice": 879,
        "price": 790,
        "discountPercentage": 10.99,
        "review": 1123,
        "rating": 4.7,
        "stock": 105,
        "brand": "Zara",
        "category": "women-western",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/l4zxn680/t-shirt/f/c/5/m-new-neck-true-basket-original-imagfrjvpyxxjmtd.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/l4zxn680/t-shirt/f/c/5/m-new-neck-true-basket-original-imagfrjvpyxxjmtd.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l4zxn680/t-shirt/1/y/s/m-new-neck-true-basket-original-imagfrjvw7yfxtgb.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l4zxn680/t-shirt/b/i/f/m-new-neck-true-basket-original-imagfrjvpuh24jfu.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l4zxn680/t-shirt/h/d/4/m-new-neck-true-basket-original-imagfrjvhjezyyst.jpeg?q=70",
        ]
    },
    {
        "id": 16,
        "title": "Embroidered Women Lace Blouse",
        "description": "Elevate your style with this exquisite Embroidered Lace Blouse. The delicate lace detailing and elegant embroidery make this blouse a perfect choice for special occasions. Made with high-quality materials, it offers a comfortable and luxurious feel. Pair it with your favorite bottoms and accessories for a sophisticated and feminine look.",
        "prevPrice": 699,
        "price": 595,
        "discountPercentage": 12.5,
        "review": 789,
        "rating": 4.8,
        "stock": 38,
        "brand": "Gucci",
        "category": "women-western",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/xif0q/shirt/h/h/r/m-t0721-chimpaaanzee-original-imafn9qrtteagrcb-bb.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/shirt/h/h/r/m-t0721-chimpaaanzee-original-imafn9qrtteagrcb-bb.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/k4d27ww0/shirt/h/h/r/l-t0721-chimpaaanzee-original-imafn9qr4genrz77.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/k4d27ww0/shirt/h/h/r/l-t0721-chimpaaanzee-original-imafn9qrqrxhzexk.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/k4d27ww0/shirt/h/h/r/l-t0721-chimpaaanzee-original-imafn9qrufh2kycr.jpeg?q=70"
        ]
    },

    {
        "id": 17,
        "title": "Sleeveless Women A-Line Dress",
        "description": "Step out in style with this chic Sleeveless A-Line Dress. The A-line silhouette and sleeveless design give this dress a modern and flattering look. Made with high-quality fabric, it offers comfort and breathability. Whether you're attending a party or a formal event, this dress is sure to make a statement and turn heads.",
        "prevPrice": 990,
        "price": 809,
        "discountPercentage": 20,
        "review": 2500,
        "rating": 4.5,
        "stock": 22,
        "brand": "Zara",
        "category": "women-western",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/4/y/v/l-cordset-d1-mehrang-original-imagnp8tg8zrmfhb.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/4/y/v/l-cordset-d1-mehrang-original-imagnp8tg8zrmfhb.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/f/m/x/l-cordset-d1-mehrang-original-imagnp8t4uzdqgmc.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/s/6/x/l-cordset-d1-mehrang-original-imagnp8tx6zxqgmx.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/k/s/t/l-cordset-d1-mehrang-original-imagnp8t5hnhzyfa.jpeg?q=70"
        ]
    },

    {
        "id": 18,
        "title": "Women Pleated Midi Skirt",
        "description": "Add a touch of elegance to your wardrobe with this sophisticated Pleated Midi Skirt. The pleated design and midi length create a timeless and classy look. Made with high-quality materials, it offers comfort and durability. Whether you're going to the office or a social event, this skirt is a versatile piece that can be dressed up or down.",
        "prevPrice": 1170,
        "price": 965,
        "discountPercentage": 10.8,
        "review": 4321,
        "rating": 4.3,
        "stock": 74,
        "brand": "Gucci",
        "category": "women-western",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/i/o/d/xxl-drsmrsy009-marisy-original-imagg8navmaxqysx.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/i/o/d/xxl-drsmrsy009-marisy-original-imagg8navmaxqysx.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/l/r/4/xxl-drsmrsy009-marisy-original-imagg8nay8edatbu.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/p/m/v/xxl-drsmrsy009-marisy-original-imagg8na7dwceywp.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/g/a/z/xxl-drsmrsy009-marisy-original-imagg8nab7afhj4p.jpeg?q=70"
        ]
    },

    {
        "id": 19,
        "title": "Women Denim Jacket",
        "description": "Stay fashionable and cool with this classic Denim Jacket. The timeless denim fabric and versatile design make it a must-have in your wardrobe. Made with high-quality denim, it offers durability and style. Pair it with your favorite jeans or dress for a trendy and effortless look that never goes out of style.",
        "prevPrice": 966,
        "price": 795,
        "discountPercentage": 15,
        "review": 1890,
        "rating": 4.7,
        "stock": 63,
        "brand": "Zara",
        "category": "women-western",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/g/k/o/m-d603-drsdrs-deklook-original-imagp25pxq3dwcwn.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/g/k/o/m-d603-drsdrs-deklook-original-imagp25pxq3dwcwn.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/w/q/i/m-d603-drsdrs-deklook-original-imagp25pgvnzymav.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/e/h/z/m-d603-drsdrs-deklook-original-imagp25pescsy4fg.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/dress/q/a/a/m-d603-drsdrs-deklook-original-imagp25phfzmkfx3.jpeg?q=70"
        ]
    },

    {
        "id": 20,
        "title": "Women Ruffle Sleeve Blouse",
        "description": "Achieve a feminine and stylish look with this elegant Ruffle Sleeve Blouse. The ruffle detailing on the sleeves adds a touch of romance and sophistication. Made with lightweight and breathable fabric, it offers comfort and versatility. Whether you're going to the office or a casual outing, this blouse is a versatile piece that can be dressed up or down.",
        "prevPrice": 970,
        "price": 899,
        "discountPercentage": 5.5,
        "review": 876,
        "rating": 4.4,
        "stock": 98,
        "brand": "Gucci",
        "category": "women-western",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/xif0q/skirt/8/x/t/l-midi-plat-otabu-original-imag4umh4yuwzds5-bb.jpeg?q=70",
        "images": [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/skirt/8/x/t/l-midi-plat-otabu-original-imag4umh4yuwzds5-bb.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/kqy3rm80/skirt/w/q/e/l-midi-plat-otabu-original-imag4umh28zmnwt5.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/kqy3rm80/skirt/j/1/2/l-midi-plat-otabu-original-imag4umhys4fqxh9.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/kqy3rm80/skirt/j/2/6/l-midi-plat-otabu-original-imag4umhygzsykdt.jpeg?q=70"
        ]
    },
    {
        "id": 21,
        "title": "Men Printed Round Neck Cotton Blend Light Blue T-Shirt",
        "description": "Fine quality Branded Product Keep in a cool and dry place",
        "prevPrice": 2870,
        "price": 2500,
        "discountPercentage": 4.81,
        "review": 18906,
        "rating": 4.44,
        "stock": 133,
        "brand": "Gucci",
        "category": "men",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/ktyp8cw0/t-shirt/3/i/u/l-14847364-mast-harbour-original-imag76r5yzsz7zrv.jpeg?q=70",
        "images": [
            "https://i.dummyjson.com/data/products/21/1.png",
            "https://i.dummyjson.com/data/products/21/2.jpg",
            "https://i.dummyjson.com/data/products/21/3.jpg"
        ]
    },
    {
        "id": 22,
        "title": "Casual Printed Cotton Blend Light Blue T-Shirt for Men",
        "description": "Product details of Bake Parlor Big Elbow Macaroni - 400 gm",
        "prevPrice": 1690,
        "price": 1399,
        "discountPercentage": 15.58,
        "review": 5643,
        "rating": 4.57,
        "stock": 146,
        "brand": "Zara",
        "category": "men",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/ku2zjww0/t-shirt/n/0/e/s-15058784-mast-harbour-original-imag7ayuvnf52wyw.jpeg?q=70",
        "images": [
            "https://i.dummyjson.com/data/products/22/1.jpg",
            "https://i.dummyjson.com/data/products/22/2.jpg",
            "https://i.dummyjson.com/data/products/22/3.jpg"
        ]
    },
    {
        "id": 23,
        "title": "Graphic Print Round Neck Light Blue Tee for Stylish Men",
        "description": "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
        "prevPrice": 1870,
        "price": 1499,
        "discountPercentage": 8.04,
        "review": 7645,
        "rating": 4.85,
        "stock": 26,
        "brand": "Puma",
        "category": "men",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/kvtuxe80/t-shirt/g/c/1/m-14847638-mast-harbour-original-imag8n2s6xagdcjz.jpeg?q=70",
        "images": [
            "https://i.dummyjson.com/data/products/23/1.jpg",
            "https://i.dummyjson.com/data/products/23/2.jpg",
            "https://i.dummyjson.com/data/products/23/3.jpg",
            "https://i.dummyjson.com/data/products/23/4.jpg",
            "https://i.dummyjson.com/data/products/23/thumbnail.jpg"
        ]
    },
    {
        "id": 24,
        "title": "Trendy Cotton Blend Light Blue T-Shirt with Printed Design for Men",
        "description": "original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji",
        "prevPrice": 4870,
        "price": 4500,
        "discountPercentage": 16.8,
        "review": 1232,
        "rating": 4.94,
        "stock": 113,
        "brand": "Adidas",
        "category": "men",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/kvzkosw0/t-shirt/c/r/h/xl-15273180-mast-harbour-original-imag8rhew6hbrgsr.jpeg?q=70",
        "images": [
            "https://i.dummyjson.com/data/products/24/1.jpg",
            "https://i.dummyjson.com/data/products/24/2.jpg",
            "https://i.dummyjson.com/data/products/24/3.jpg",
            "https://i.dummyjson.com/data/products/24/4.jpg",
            "https://i.dummyjson.com/data/products/24/thumbnail.jpg"
        ]
    },
    {
        "id": 25,
        "title": "Fashionable Round Neck Light Blue Tee with Men's Prin",
        "description": "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
        "prevPrice": 1570,
        "price": 1233,
        "discountPercentage": 13.58,
        "review": 10987,
        "rating": 4.87,
        "stock": 47,
        "brand": "Gucci",
        "category": "men",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/kfoapow0-0/t-shirt/1/9/i/l-2314400-hrx-by-hrithik-roshan-original-imafw2k7ewbdgwhb.jpeg?q=70",
        "images": [
            "https://i.dummyjson.com/data/products/25/1.png",
            "https://i.dummyjson.com/data/products/25/2.jpg",
            "https://i.dummyjson.com/data/products/25/3.png",
            "https://i.dummyjson.com/data/products/25/4.jpg",
            "https://i.dummyjson.com/data/products/25/thumbnail.jpg"
        ]
    },
    {
        "id": 26,
        "title": "Abstract Pattern Cotton Blend Light Blue T-Shirt for Men",
        "description": "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
        "prevPrice": 1365,
        "price": 1100,
        "discountPercentage": 17.86,
        "review": 12345,
        "rating": 4.08,
        "stock": 131,
        "brand": "hrx",
        "category": "men",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/khglj0w0/t-shirt/4/y/3/l-ez-tshirtss-skull-center-maroon-ezdeals-original-imafxh3qfp3vqgmv.jpeg?q=70",
        "images": [
            "https://i.dummyjson.com/data/products/26/1.jpg",
            "https://i.dummyjson.com/data/products/26/2.jpg",
            "https://i.dummyjson.com/data/products/26/3.jpg",
            "https://i.dummyjson.com/data/products/26/4.jpg",
            "https://i.dummyjson.com/data/products/26/5.jpg",
            "https://i.dummyjson.com/data/products/26/thumbnail.jpg"
        ]
    },
    {
        "id": 27,
        "title": "Modern Printed Round Neck Light Blue Tee for Men's Fashion",
        "description": "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
        "prevPrice": 870,
        "price": 789,
        "discountPercentage": 15.58,
        "review": 8798,
        "rating": 4.41,
        "stock": 17,
        "brand": "mast",
        "category": "men",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/kflftzk0-0/t-shirt/a/w/p/m-10106267-hrx-by-hrithik-roshan-original-imafwyf82mjvzset.jpeg?q=70",
        "images": [
            "https://i.dummyjson.com/data/products/27/1.jpg",
            "https://i.dummyjson.com/data/products/27/2.jpg",
            "https://i.dummyjson.com/data/products/27/3.jpg",
            "https://i.dummyjson.com/data/products/27/4.jpg",
            "https://i.dummyjson.com/data/products/27/thumbnail.webp"
        ]
    },
    {
        "id": 28,
        "title": "Stylish Light Blue T-Shirt with Unique Print for Men",
        "description": "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
        "prevPrice": 870,
        "price": 765,
        "discountPercentage": 16.49,
        "review": 1221,
        "rating": 4.82,
        "stock": 54,
        "brand": "mast ",
        "category": "men",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/jvfk58w0/t-shirt/x/g/d/l-hrxss18mk-1001-a-hrx-by-hrithik-roshan-original-imafgc26zjagpcdq.jpeg?q=70",
        "images": [
            "https://i.dummyjson.com/data/products/28/1.jpg",
            "https://i.dummyjson.com/data/products/28/2.jpg",
            "https://i.dummyjson.com/data/products/28/3.png",
            "https://i.dummyjson.com/data/products/28/4.jpg",
            "https://i.dummyjson.com/data/products/28/thumbnail.jpg"
        ]
    },
    {
        "id": 29,
        "title": "Contemporary Cotton Blend Light Blue T-Shirt with Graphic Design for Men",
        "description": "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
        "prevPrice": 3870,
        "price": 3199,
        "discountPercentage": 15.34,
        "review": 11098,
        "rating": 4.44,
        "stock": 7,
        "brand": "Zara",
        "category": "men",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-t-shirt/q/m/l/m-sh-tl-m-hs-03-p1-mrn-triangletees-original-imagznfhcgd5wyaj.jpeg?q=70",
        "images": [
            "https://i.dummyjson.com/data/products/29/1.jpg",
            "https://i.dummyjson.com/data/products/29/2.jpg",
            "https://i.dummyjson.com/data/products/29/3.webp",
            "https://i.dummyjson.com/data/products/29/4.webp",
            "https://i.dummyjson.com/data/products/29/thumbnail.webp"
        ]
    },
    {
        "id": 30,
        "title": "Artistic Round Neck Light Blue Tee with Printed Motif for Men",
        "description": "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
        "prevPrice": 1170,
        "price": 879,
        "discountPercentage": 2.92,
        "review": 4563,
        "rating": 4.2,
        "stock": 54,
        "brand": "Gucci",
        "category": "men",
        "thumbnail": "https://rukminim1.flixcart.com/image/612/612/xif0q/t-shirt/9/1/o/m-db1024-42-3bros-original-imagz8zkvwjtayrs.jpeg?q=70",
        "images": [
            "https://i.dummyjson.com/data/products/30/1.jpg",
            "https://i.dummyjson.com/data/products/30/2.jpg",
            "https://i.dummyjson.com/data/products/30/3.jpg",
            "https://i.dummyjson.com/data/products/30/thumbnail.jpg"
        ]
    },

    // yahan tk done hai 
    {
        "id": 31,
        "title": "Mornadi Velvet Bed",
        "description": "Mornadi Velvet Bed Base with Headboard Slats Support Classic Style Bedroom Furniture Bed Set",
        "prevPrice": 1870,
        "price": 1233,
        "discountPercentage": 17,
        "review": 129089,
        "rating": 4.6,
        "stock": 140,
        "brand": "Furniture Bed Set",
        "category": "kids",
        "thumbnail": "https://i.dummyjson.com/data/products/31/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/31/1.jpg",
            "https://i.dummyjson.com/data/products/31/2.jpg",
            "https://i.dummyjson.com/data/products/31/3.jpg",
            "https://i.dummyjson.com/data/products/31/4.jpg",
            "https://i.dummyjson.com/data/products/31/thumbnail.jpg"
        ]
    },
    {
        "id": 32,
        "title": "Sofa for Coffe Cafe",
        "description": "Ratttan Outdoor furniture Set Waterproof  Rattan Sofa for Coffe Cafe",
        "prevPrice": 4870,
        "price": 4122,
        "discountPercentage": 15.59,
        "review": 1987,
        "rating": 4.4,
        "stock": 30,
        "brand": "Ratttan Outdoor",
        "category": "kids",
        "thumbnail": "https://i.dummyjson.com/data/products/32/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/32/1.jpg",
            "https://i.dummyjson.com/data/products/32/2.jpg",
            "https://i.dummyjson.com/data/products/32/3.jpg",
            "https://i.dummyjson.com/data/products/32/thumbnail.jpg"
        ]
    },
    {
        "id": 33,
        "title": "3 Tier Corner Shelves",
        "description": "3 Tier Corner Shelves | 3 PCs Wall Mount Kitchen Shelf | Floating Bedroom Shelf",
        "prevPrice": 1470,
        "price": 1122,
        "discountPercentage": 17,
        "review": 1234,
        "rating": 4.31,
        "stock": 106,
        "brand": "Kitchen Shelf",
        "category": "kids",
        "thumbnail": "https://i.dummyjson.com/data/products/33/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/33/1.jpg",
            "https://i.dummyjson.com/data/products/33/2.jpg",
            "https://i.dummyjson.com/data/products/33/3.jpg",
            "https://i.dummyjson.com/data/products/33/4.jpg",
            "https://i.dummyjson.com/data/products/33/thumbnail.jpg"
        ]
    },
    {
        "id": 34,
        "title": "Plastic Table",
        "description": "Very good quality plastic table for multi purpose now in reasonable price",
        "prevPrice": 1090,
        "price": 988,
        "discountPercentage": 4,
        "review": 12342,
        "rating": 4.01,
        "stock": 136,
        "brand": "Multi Purpose",
        "category": "kids",
        "thumbnail": "https://i.dummyjson.com/data/products/34/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/34/1.jpg",
            "https://i.dummyjson.com/data/products/34/2.jpg",
            "https://i.dummyjson.com/data/products/34/3.jpg",
            "https://i.dummyjson.com/data/products/34/4.jpg",
            "https://i.dummyjson.com/data/products/34/thumbnail.jpg"
        ]
    },
    {
        "id": 35,
        "title": "3 DOOR PORTABLE",
        "description": "Material: Stainless Steel and Fabric  Item Size: 110 cm x 45 cm x 175 cm Package Contents: 1 Storage Wardrobe",
        "prevPrice": 870,
        "price": 768,
        "discountPercentage": 7.98,
        "review": 12987,
        "rating": 4.6,
        "stock": 68,
        "brand": "AmnaMart",
        "category": "kids",
        "thumbnail": "https://i.dummyjson.com/data/products/35/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/35/1.jpg",
            "https://i.dummyjson.com/data/products/35/2.jpg",
            "https://i.dummyjson.com/data/products/35/3.jpg",
            "https://i.dummyjson.com/data/products/35/4.jpg",
            "https://i.dummyjson.com/data/products/35/thumbnail.jpg"
        ]
    },
    {
        "id": 36,
        "title": "Sleeve Shirt Womens",
        "description": "Cotton Solid Color Professional Wear Sleeve Shirt Womens Work Blouses Wholesale Clothing Casual Plain Custom Top OEM Customized",
        "prevPrice": 1170,
        "price": 998,
        "discountPercentage": 10.89,
        "review": 44332,
        "rating": 4.26,
        "stock": 39,
        "brand": "Professional Wear",
        "category": "kids",
        "thumbnail": "https://i.dummyjson.com/data/products/36/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/36/1.jpg",
            "https://i.dummyjson.com/data/products/36/2.webp",
            "https://i.dummyjson.com/data/products/36/3.webp",
            "https://i.dummyjson.com/data/products/36/4.jpg",
            "https://i.dummyjson.com/data/products/36/thumbnail.jpg"
        ]
    },
    {
        "id": 37,
        "title": "ank Tops for Womens/Girls",
        "description": "PACK OF 3 CAMISOLES ,VERY COMFORTABLE SOFT COTTON STUFF, COMFORTABLE IN ALL FOUR SEASONS",
        "prevPrice": 870,
        "price": 543,
        "discountPercentage": 12.05,
        "review": 12353,
        "rating": 4.2,
        "stock": 107,
        "brand": "Soft Cotton",
        "category": "kids",
        "thumbnail": "https://i.dummyjson.com/data/products/37/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/37/1.jpg",
            "https://i.dummyjson.com/data/products/37/2.jpg",
            "https://i.dummyjson.com/data/products/37/3.jpg",
            "https://i.dummyjson.com/data/products/37/4.jpg",
            "https://i.dummyjson.com/data/products/37/thumbnail.jpg"
        ]
    },
    {
        "id": 38,
        "title": "sublimation plain kids tank",
        "description": "sublimation plain kids tank tops wholesale",
        "prevPrice": 851,
        "price": 600,
        "discountPercentage": 11.12,
        "review": 1233,
        "rating": 4.8,
        "stock": 20,
        "brand": "Soft Cotton",
        "category": "kids",
        "thumbnail": "https://i.dummyjson.com/data/products/38/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/38/1.png",
            "https://i.dummyjson.com/data/products/38/2.jpg",
            "https://i.dummyjson.com/data/products/38/3.jpg",
            "https://i.dummyjson.com/data/products/38/4.jpg"
        ]
    },
    {
        "id": 39,
        "title": "Women Sweaters Wool",
        "description": "2021 Custom Winter Fall Zebra Knit Crop Top Women Sweaters Wool Mohair Cos Customize Crew Neck Women' S Crop Top Sweater",
        "prevPrice": 570,
        "price": 344,
        "discountPercentage": 17.2,
        "rating": 4.5,
        "review": 7654,
        "stock": 55,
        "brand": "Top Sweater",
        "category": "kids",
        "thumbnail": "https://i.dummyjson.com/data/products/39/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/39/1.jpg",
            "https://i.dummyjson.com/data/products/39/2.jpg",
            "https://i.dummyjson.com/data/products/39/3.jpg",
            "https://i.dummyjson.com/data/products/39/4.jpg",
            "https://i.dummyjson.com/data/products/39/thumbnail.jpg"
        ]
    },
    {
        "id": 40,
        "title": "women winter clothes",
        "description": "women winter clothes thick fleece hoodie top with sweat pantjogger women sweatsuit set joggers pants two piece pants set",
        "prevPrice": 470,
        "price": 299,
        "discountPercentage": 13.39,
        "review": 449787,
        "rating": 4.9,
        "stock": 84,
        "brand": "Top Sweater",
        "category": "kids",
        "thumbnail": "https://i.dummyjson.com/data/products/40/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/40/1.jpg",
            "https://i.dummyjson.com/data/products/40/2.jpg"
        ]
    },
    {
        "id": 41,
        "title": "NIGHT SUIT",
        "description": "NIGHT SUIT RED MICKY MOUSE..  For Girls. Fantastic Suits.",
        "prevPrice": 998,
        "price": 670,
        "discountPercentage": 15.05,
        "review": 5432,
        "rating": 4.65,
        "stock": 21,
        "brand": "RED MICKY MOUSE..",
        "category": "home",
        "thumbnail": "https://i.dummyjson.com/data/products/41/thumbnail.webp",
        "images": [
            "https://i.dummyjson.com/data/products/41/1.jpg",
            "https://i.dummyjson.com/data/products/41/2.webp",
            "https://i.dummyjson.com/data/products/41/3.jpg",
            "https://i.dummyjson.com/data/products/41/4.jpg",
            "https://i.dummyjson.com/data/products/41/thumbnail.webp"
        ]
    },
    {
        "id": 42,
        "title": "Stiched Kurta plus trouser",
        "description": "FABRIC: LILEIN CHEST: 21 LENGHT: 37 TROUSER: (38) :ARABIC LILEIN",
        "prevPrice": 1470,
        "price": 1123,
        "discountPercentage": 15.37,
        "review": 1211,
        "rating": 4.05,
        "stock": 148,
        "brand": "Digital Printed",
        "category": "home",
        "thumbnail": "https://i.dummyjson.com/data/products/42/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/42/1.png",
            "https://i.dummyjson.com/data/products/42/2.png",
            "https://i.dummyjson.com/data/products/42/3.png",
            "https://i.dummyjson.com/data/products/42/4.jpg",
            "https://i.dummyjson.com/data/products/42/thumbnail.jpg"
        ]
    },
    {
        "id": 43,
        "title": "frock gold printed",
        "description": "Ghazi fabric long frock gold printed ready to wear stitched collection (G992)",
        "prevPrice": 1111,
        "price": 976,
        "discountPercentage": 15.55,
        "review": 4487,
        "rating": 4.31,
        "stock": 150,
        "brand": "Ghazi Fabric",
        "category": "home",
        "thumbnail": "https://i.dummyjson.com/data/products/43/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/43/1.jpg",
            "https://i.dummyjson.com/data/products/43/2.jpg",
            "https://i.dummyjson.com/data/products/43/3.jpg",
            "https://i.dummyjson.com/data/products/43/4.jpg",
            "https://i.dummyjson.com/data/products/43/thumbnail.jpg"
        ]
    },
    {
        "id": 44,
        "title": "Ladies Multicolored Dress",
        "description": "This classy shirt for women gives you a gorgeous look on everyday wear and specially for semi-casual wears.",
        "prevPrice": 888,
        "price": 790,
        "discountPercentage": 16.88,
        "review": 44871,
        "rating": 4.03,
        "stock": 2,
        "brand": "Ghazi Fabric",
        "category": "home",
        "thumbnail": "https://i.dummyjson.com/data/products/44/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/44/1.jpg",
            "https://i.dummyjson.com/data/products/44/2.jpg",
            "https://i.dummyjson.com/data/products/44/3.jpg",
            "https://i.dummyjson.com/data/products/44/4.jpg",
            "https://i.dummyjson.com/data/products/44/thumbnail.jpg"
        ]
    },
    {
        "id": 45,
        "title": "Malai Maxi Dress",
        "description": "Ready to wear, Unique design according to modern standard fashion, Best fitting ,Imported stuff",
        "prevPrice": 3488,
        "price": 3199,
        "discountPercentage": 5.07,
        "review": 4483,
        "rating": 4.67,
        "stock": 96,
        "brand": "IELGY",
        "category": "home",
        "thumbnail": "https://i.dummyjson.com/data/products/45/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/45/1.jpg",
            "https://i.dummyjson.com/data/products/45/2.webp",
            "https://i.dummyjson.com/data/products/45/3.jpg",
            "https://i.dummyjson.com/data/products/45/4.jpg",
            "https://i.dummyjson.com/data/products/45/thumbnail.jpg"
        ]
    },
    {
        "id": 46,
        "title": "women's shoes",
        "description": "Close: Lace, Style with bottom: Increased inside, Sole Material: Rubber",
        "prevPrice": 5870,
        "price": 5400,
        "discountPercentage": 16.96,
        "review": 4437,
        "rating": 4.14,
        "stock": 72,
        "brand": "IELGY fashion",
        "category": "home",
        "thumbnail": "https://i.dummyjson.com/data/products/46/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/46/1.webp",
            "https://i.dummyjson.com/data/products/46/2.jpg",
            "https://i.dummyjson.com/data/products/46/3.jpg",
            "https://i.dummyjson.com/data/products/46/4.jpg",
            "https://i.dummyjson.com/data/products/46/thumbnail.jpg"
        ]
    },
    {
        "id": 47,
        "title": "Sneaker shoes",
        "description": "Synthetic Leather Casual Sneaker shoes for Women/girls Sneakers For Women",
        "prevPrice": 1399,
        "price": 1200,
        "discountPercentage": 10.37,
        "review": 4427,
        "rating": 4.19,
        "stock": 50,
        "brand": "Synthetic Leather",
        "category": "home",
        "thumbnail": "https://i.dummyjson.com/data/products/47/thumbnail.jpeg",
        "images": [
            "https://i.dummyjson.com/data/products/47/1.jpg",
            "https://i.dummyjson.com/data/products/47/2.jpg",
            "https://i.dummyjson.com/data/products/47/3.jpg",
            "https://i.dummyjson.com/data/products/47/thumbnail.jpeg"
        ]
    },
    {
        "id": 48,
        "title": "Women Strip Heel",
        "description": "Features: Flip-flops, Mid Heel, Comfortable, Striped Heel, Antiskid, Striped",
        "prevPrice": 678,
        "price": 400,
        "discountPercentage": 10.83,
        "review": 417,
        "rating": 4.02,
        "stock": 25,
        "brand": "Sandals Flip Flops",
        "category": "home",
        "thumbnail": "https://i.dummyjson.com/data/products/48/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/48/1.jpg",
            "https://i.dummyjson.com/data/products/48/2.jpg",
            "https://i.dummyjson.com/data/products/48/3.jpg",
            "https://i.dummyjson.com/data/products/48/4.jpg",
            "https://i.dummyjson.com/data/products/48/thumbnail.jpg"
        ]
    },
    {
        "id": 49,
        "title": "Chappals & Shoe Ladies Metallic",
        "description": "Womens Chappals & Shoe Ladies Metallic Tong Thong Sandal Flat Summer 2020 Maasai Sandals",
        "prevPrice": 499,
        "price": 293,
        "discountPercentage": 2.62,
        "review": 4287,
        "rating": 4.72,
        "stock": 107,
        "brand": "Maasai Sandals",
        "category": "home",
        "thumbnail": "https://i.dummyjson.com/data/products/49/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/49/1.jpg",
            "https://i.dummyjson.com/data/products/49/2.jpg",
            "https://i.dummyjson.com/data/products/49/3.webp",
            "https://i.dummyjson.com/data/products/49/thumbnail.jpg"
        ]
    },
    {
        "id": 50,
        "title": "Women Shoes",
        "description": "2020 New Arrivals Genuine Leather Fashion Trend Platform Summer Women Shoes",
        "prevPrice": 1000,
        "price": 936,
        "discountPercentage": 16.87,
        "review": 446,
        "rating": 4.3,
        "stock": 46,
        "brand": "Arrivals Genuine",
        "category": "home",
        "thumbnail": "https://i.dummyjson.com/data/products/50/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/50/1.jpeg",
            "https://i.dummyjson.com/data/products/50/2.jpg",
            "https://i.dummyjson.com/data/products/50/3.jpg"
        ]
    },
    {
        "id": 51,
        "title": "half sleeves T shirts",
        "description": "Many store is creating new designs and trend every month and every year. Daraz.pk have a beautiful range of men fashion brands",
        "prevPrice": 870,
        "price": 723,
        "discountPercentage": 12.76,
        "review": 687,
        "rating": 4.26,
        "stock": 132,
        "brand": "Vintage Apparel",
        "category": "beauty",
        "thumbnail": "https://i.dummyjson.com/data/products/51/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/51/1.png",
            "https://i.dummyjson.com/data/products/51/2.jpg",
            "https://i.dummyjson.com/data/products/51/3.jpg",
            "https://i.dummyjson.com/data/products/51/thumbnail.jpg"
        ]
    },
    {
        "id": 52,
        "title": "FREE FIRE T Shirt",
        "description": "quality and professional print - It doesn't just look high quality, it is high quality.",
        "prevPrice": 1188,
        "price": 710,
        "discountPercentage": 14.72,
        "review": 4347,
        "rating": 4.52,
        "stock": 128,
        "brand": "FREE FIRE",
        "category": "beauty",
        "thumbnail": "https://i.dummyjson.com/data/products/52/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/52/1.png",
            "https://i.dummyjson.com/data/products/52/2.png",
            "https://i.dummyjson.com/data/products/52/3.jpg",
            "https://i.dummyjson.com/data/products/52/4.jpg",
            "https://i.dummyjson.com/data/products/52/thumbnail.jpg"
        ]
    },
    {
        "id": 53,
        "title": "printed high quality T shirts",
        "description": "Brand: vintage Apparel ,Export quality",
        "prevPrice": 870,
        "price": 635,
        "discountPercentage": 7.54,
        "review": 6787,
        "rating": 4.89,
        "stock": 6,
        "brand": "Vintage Apparel",
        "category": "beauty",
        "thumbnail": "https://i.dummyjson.com/data/products/53/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/53/1.webp",
            "https://i.dummyjson.com/data/products/53/2.jpg",
            "https://i.dummyjson.com/data/products/53/3.jpg",
            "https://i.dummyjson.com/data/products/53/4.jpg",
            "https://i.dummyjson.com/data/products/53/thumbnail.jpg"
        ]
    },
    {
        "id": 54,
        "title": "Pubg Printed Graphic T-Shirt",
        "description": "Product Description Features: 100% Ultra soft Polyester Jersey. Vibrant & colorful printing on front. Feels soft as cotton without ever cracking",
        "prevPrice": 570,
        "price": 460,
        "discountPercentage": 16.44,
        "review": 44587,
        "rating": 4.62,
        "stock": 136,
        "brand": "The Warehouse",
        "category": "beauty",
        "thumbnail": "https://i.dummyjson.com/data/products/54/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/54/1.jpg",
            "https://i.dummyjson.com/data/products/54/2.jpg",
            "https://i.dummyjson.com/data/products/54/3.jpg",
            "https://i.dummyjson.com/data/products/54/4.jpg",
            "https://i.dummyjson.com/data/products/54/thumbnail.jpg"
        ]
    },
    {
        "id": 55,
        "title": "Money Heist Printed Summer T Shirts",
        "description": "Fabric Jercy, Size: M & L Wear Stylish Dual Stiched",
        "prevPrice": 799,
        "price": 466,
        "discountPercentage": 15.97,
        "review": 78987,
        "rating": 4.9,
        "stock": 122,
        "brand": "The Warehouse",
        "category": "beauty",
        "thumbnail": "https://i.dummyjson.com/data/products/55/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/55/1.jpg",
            "https://i.dummyjson.com/data/products/55/2.webp",
            "https://i.dummyjson.com/data/products/55/3.jpg",
            "https://i.dummyjson.com/data/products/55/4.jpg",
            "https://i.dummyjson.com/data/products/55/thumbnail.jpg"
        ]
    },
    {
        "id": 56,
        "title": "Sneakers Joggers Shoes",
        "description": "Gender: Men , Colors: Same as DisplayedCondition: 100% Brand New",
        "prevPrice": 1870,
        "price": 1490,
        "discountPercentage": 12.57,
        "review": 14487,
        "rating": 4.8,
        "stock": 6,
        "brand": "Sneakers",
        "category": "beauty",
        "thumbnail": "https://i.dummyjson.com/data/products/56/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/56/1.jpg",
            "https://i.dummyjson.com/data/products/56/2.jpg",
            "https://i.dummyjson.com/data/products/56/3.jpg",
            "https://i.dummyjson.com/data/products/56/4.jpg",
            "https://i.dummyjson.com/data/products/56/5.jpg",
            "https://i.dummyjson.com/data/products/56/thumbnail.jpg"
        ]
    },
    {
        "id": 57,
        "title": "Loafers for men",
        "description": "Men Shoes - Loafers for men - Rubber Shoes - Nylon Shoes - Shoes for men - Moccassion - Pure Nylon (Rubber) Expot Quality.",
        "prevPrice": 677,
        "price": 447,
        "discountPercentage": 10.91,
        "review": 44873,
        "rating": 4.91,
        "stock": 20,
        "brand": "Rubber",
        "category": "beauty",
        "thumbnail": "https://i.dummyjson.com/data/products/57/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/57/1.jpg",
            "https://i.dummyjson.com/data/products/57/2.jpg",
            "https://i.dummyjson.com/data/products/57/3.jpg",
            "https://i.dummyjson.com/data/products/57/4.jpg",
            "https://i.dummyjson.com/data/products/57/thumbnail.jpg"
        ]
    },
    {
        "id": 58,
        "title": "formal offices shoes",
        "description": "Pattern Type: Solid, Material: PU, Toe Shape: Pointed Toe ,Outsole Material: Rubber",
        "prevPrice": 777,
        "price": 757,
        "discountPercentage": 12,
        "review": 2487,
        "rating": 4.1,
        "stock": 68,
        "brand": "The Warehouse",
        "category": "beauty",
        "thumbnail": "https://i.dummyjson.com/data/products/58/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/58/1.jpg",
            "https://i.dummyjson.com/data/products/58/2.jpg",
            "https://i.dummyjson.com/data/products/58/3.jpg",
            "https://i.dummyjson.com/data/products/58/4.jpg",
            "https://i.dummyjson.com/data/products/58/thumbnail.jpg"
        ]
    },
    {
        "id": 59,
        "title": "Spring and summershoes",
        "description": "Comfortable stretch cloth, lightweight body; ,rubber sole, anti-skid wear;",
        "prevPrice": 3170,
        "price": 2900,
        "discountPercentage": 8.71,
        "review": 44567,
        "rating": 4.33,
        "stock": 137,
        "brand": "Sneakers",
        "category": "beauty",
        "thumbnail": "https://i.dummyjson.com/data/products/59/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/59/1.jpg",
            "https://i.dummyjson.com/data/products/59/2.jpg",
            "https://i.dummyjson.com/data/products/59/3.jpg",
            "https://i.dummyjson.com/data/products/59/4.jpg",
            "https://i.dummyjson.com/data/products/59/thumbnail.jpg"
        ]
    },
    {
        "id": 60,
        "title": "Stylish Casual Jeans Shoes",
        "description": "High Quality ,Stylish design ,Comfortable wear ,FAshion ,Durable",
        "prevPrice": 870,
        "price": 598,
        "discountPercentage": 7.55,
        "review": 12354,
        "rating": 4.55,
        "stock": 129,
        "brand": "Sneakers",
        "category": "beauty",
        "thumbnail": "https://i.dummyjson.com/data/products/60/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/60/1.jpg",
            "https://i.dummyjson.com/data/products/60/2.jpg",
            "https://i.dummyjson.com/data/products/60/3.jpg",
            "https://i.dummyjson.com/data/products/60/thumbnail.jpg"
        ]
    },
    {
        "id": 61,
        "title": "Leather Straps Wristwatch",
        "description": "Style:Sport ,Clasp:Buckles ,Water Resistance Depth:3Bar",
        "prevPrice": 1370,
        "price": 1120,
        "discountPercentage": 7.14,
        "review": 4455,
        "rating": 4.63,
        "stock": 91,
        "brand": "Naviforce",
        "category": "jewellery",
        "thumbnail": "https://i.dummyjson.com/data/products/61/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/61/1.jpg",
            "https://i.dummyjson.com/data/products/61/2.png",
            "https://i.dummyjson.com/data/products/61/3.jpg"
        ]
    },
    {
        "id": 62,
        "title": "Waterproof Leather Brand Watch",
        "description": "Watch Crown With Environmental IPS Bronze Electroplating; Display system of 12 hours",
        "prevPrice": 871,
        "price": 699,
        "discountPercentage": 3.15,
        "review": 1121,
        "rating": 4.05,
        "stock": 95,
        "brand": "SKMEI 9117",
        "category": "jewellery",
        "thumbnail": "https://i.dummyjson.com/data/products/62/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/62/1.jpg",
            "https://i.dummyjson.com/data/products/62/2.jpg"
        ]
    },
    {
        "id": 63,
        "title": "Royal Blue Premium Watch",
        "description": "Men Silver Chain Royal Blue Premium Watch Latest Analog Watch",
        "prevPrice": 1070,
        "price": 980,
        "discountPercentage": 2.56,
        "review": 1221,
        "rating": 4.89,
        "stock": 142,
        "brand": "SKMEI 9117",
        "category": "jewellery",
        "thumbnail": "https://i.dummyjson.com/data/products/63/thumbnail.webp",
        "images": [
            "https://i.dummyjson.com/data/products/63/1.jpg",
            "https://i.dummyjson.com/data/products/63/2.jpg",
            "https://i.dummyjson.com/data/products/63/3.png",
            "https://i.dummyjson.com/data/products/63/4.jpeg"
        ]
    },
    {
        "id": 64,
        "title": "Leather Strap Skeleton Watch",
        "description": "Leather Strap Skeleton Watch for Men - Stylish and Latest Design",
        "prevPrice": 1170,
        "price": 765,
        "discountPercentage": 10.2,
        "review": 43387,
        "rating": 4.8,
        "stock": 61,
        "brand": "Strap Skeleton",
        "category": "jewellery",
        "thumbnail": "https://i.dummyjson.com/data/products/64/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/64/1.jpg",
            "https://i.dummyjson.com/data/products/64/2.webp",
            "https://i.dummyjson.com/data/products/64/3.jpg",
            "https://i.dummyjson.com/data/products/64/thumbnail.jpg"
        ]
    },
    {
        "id": 65,
        "title": "Stainless Steel Wrist Watch",
        "description": "Stylish Watch For Man (Luxury) Classy Men's Stainless Steel Wrist Watch - Box Packed",
        "prevPrice": 870,
        "price": 799,
        "discountPercentage": 17.79,
        "review": 44847,
        "rating": 4.7,
        "stock": 94,
        "brand": "Stainless",
        "category": "jewellery",
        "thumbnail": "https://i.dummyjson.com/data/products/65/thumbnail.webp",
        "images": [
            "https://i.dummyjson.com/data/products/65/1.jpg",
            "https://i.dummyjson.com/data/products/65/2.webp",
            "https://i.dummyjson.com/data/products/65/3.jpg",
            "https://i.dummyjson.com/data/products/65/4.webp",
            "https://i.dummyjson.com/data/products/65/thumbnail.webp"
        ]
    },
    {
        "id": 66,
        "title": "Steel Analog Couple Watches",
        "description": "Elegant design, Stylish ,Unique & Trendy,Comfortable wear",
        "prevPrice": 970,
        "price": 899,
        "discountPercentage": 3.23,
        "review": 442387,
        "rating": 4.7,
        "stock": 24,
        "brand": "Eastern Watches",
        "category": "jewellery",
        "thumbnail": "https://i.dummyjson.com/data/products/66/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/66/1.jpg",
            "https://i.dummyjson.com/data/products/66/2.jpg",
            "https://i.dummyjson.com/data/products/66/3.jpg",
            "https://i.dummyjson.com/data/products/66/4.JPG",
            "https://i.dummyjson.com/data/products/66/thumbnail.jpg"
        ]
    },
    {
        "id": 67,
        "title": "Fashion Magnetic Wrist Watch",
        "description": "Buy this awesome  The product is originally manufactured by the company and it's a top selling product with a very reasonable",
        "prevPrice": 1070,
        "price": 999,
        "discountPercentage": 16.69,
        "review": 4487,
        "rating": 4.3,
        "stock": 46,
        "brand": "Eastern Watches",
        "category": "jewellery",
        "thumbnail": "https://i.dummyjson.com/data/products/67/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/67/1.jpg",
            "https://i.dummyjson.com/data/products/67/2.jpg",
            "https://i.dummyjson.com/data/products/67/3.jpg",
            "https://i.dummyjson.com/data/products/67/4.jpg",
            "https://i.dummyjson.com/data/products/67/thumbnail.jpg"
        ]
    },
    {
        "id": 68,
        "title": "Stylish Luxury Digital Watch",
        "description": "Stylish Luxury Digital Watch For Girls / Women - Led Smart Ladies Watches For Girls",
        "prevPrice": 888,
        "price": 788,
        "discountPercentage": 9.03,
        "review": 447,
        "rating": 3.9,
        "stock": 77,
        "brand": "Luxury Digital",
        "category": "jewellery",
        "thumbnail": "https://i.dummyjson.com/data/products/68/thumbnail.webp",
        "images": [
            "https://i.dummyjson.com/data/products/68/1.jpg",
            "https://i.dummyjson.com/data/products/68/2.jpg"
        ]
    },
    {
        "id": 69,
        "title": "Golden Watch Pearls Bracelet Watch",
        "description": "Product details of Golden Watch Pearls Bracelet Watch For Girls - Golden Chain Ladies Bracelate Watch for Women",
        "prevPrice": 1170,
        "price": 967,
        "discountPercentage": 17.55,
        "review": 44187,
        "rating": 4.7,
        "stock": 89,
        "brand": "Watch Pearls",
        "category": "jewellery",
        "thumbnail": "https://i.dummyjson.com/data/products/69/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/69/1.jpg",
            "https://i.dummyjson.com/data/products/69/2.jpg",
            "https://i.dummyjson.com/data/products/69/3.webp",
            "https://i.dummyjson.com/data/products/69/4.jpg",
            "https://i.dummyjson.com/data/products/69/thumbnail.jpg"
        ]
    },
    {
        "id": 70,
        "title": "Stainless Steel Women",
        "description": "Fashion Skmei 1830 Shell Dial Stainless Steel Women Wrist Watch Lady Bracelet Watch Quartz Watches Ladies",
        "prevPrice": 1070,
        "price": 977,
        "discountPercentage": 8.98,
        "review": 1237,
        "rating": 4.8,
        "stock": 111,
        "brand": "Bracelet",
        "category": "jewellery",
        "thumbnail": "https://i.dummyjson.com/data/products/70/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/70/1.jpg",
            "https://i.dummyjson.com/data/products/70/2.jpg",
            "https://i.dummyjson.com/data/products/70/thumbnail.jpg"
        ]
    },
    {
        "id": 71,
        "title": "Women Shoulder Bags",
        "description": "LouisWill Women Shoulder Bags Long Clutches Cross Body Bags Phone Bags PU Leather Hand Bags Large Capacity Card Holders Zipper Coin Purses Fashion Crossbody Bags for Girls Ladies",
        "prevPrice": 870,
        "price": 688,
        "discountPercentage": 14.65,
        "review": 14487,
        "rating": 4.1,
        "stock": 17,
        "brand": "LouisWill",
        "category": "bags",
        "thumbnail": "https://i.dummyjson.com/data/products/71/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/71/1.jpg",
            "https://i.dummyjson.com/data/products/71/2.jpg",
            "https://i.dummyjson.com/data/products/71/3.webp",
            "https://i.dummyjson.com/data/products/71/thumbnail.jpg"
        ]
    },
    {
        "id": 72,
        "title": "Handbag For Girls",
        "description": "This fashion is designed to add a charming effect to your casual outfit. This Bag is made of synthetic leather.",
        "prevPrice": 1170,
        "price": 965,
        "discountPercentage": 17.5,
        "review": 44387,
        "rating": 4.9,
        "stock": 27,
        "brand": "LouisWill",
        "category": "bags",
        "thumbnail": "https://i.dummyjson.com/data/products/72/thumbnail.webp",
        "images": [
            "https://i.dummyjson.com/data/products/72/1.jpg",
            "https://i.dummyjson.com/data/products/72/2.png",
            "https://i.dummyjson.com/data/products/72/3.webp",
            "https://i.dummyjson.com/data/products/72/4.jpg",
            "https://i.dummyjson.com/data/products/72/thumbnail.webp"
        ]
    },
    {
        "id": 73,
        "title": "Fancy hand clutch",
        "description": "This fashion is designed to add a charming effect to your casual outfit. This Bag is made of synthetic leather.",
        "prevPrice": 570,
        "price": 456,
        "discountPercentage": 10.39,
        "review": 457,
        "rating": 4.1,
        "stock": 101,
        "brand": "Bracelet",
        "category": "bags",
        "thumbnail": "https://i.dummyjson.com/data/products/73/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/73/1.jpg",
            "https://i.dummyjson.com/data/products/73/2.webp",
            "https://i.dummyjson.com/data/products/73/3.jpg",
            "https://i.dummyjson.com/data/products/73/thumbnail.jpg"
        ]
    },
    {
        "id": 74,
        "title": "Leather Hand Bag",
        "description": "It features an attractive design that makes it a must have accessory in your collection. We sell different kind of bags for boys, kids, women, girls and also for unisex.",
        "prevPrice": 1070,
        "price": 987,
        "discountPercentage": 11.19,
        "review": 2487,
        "rating": 4.1,
        "stock": 43,
        "brand": "Copenhagen Luxe",
        "category": "bags",
        "thumbnail": "https://i.dummyjson.com/data/products/74/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/74/1.jpg",
            "https://i.dummyjson.com/data/products/74/2.jpg",
            "https://i.dummyjson.com/data/products/74/3.jpg",
            "https://i.dummyjson.com/data/products/74/4.jpg",
            "https://i.dummyjson.com/data/products/74/thumbnail.jpg"
        ]
    },
    {
        "id": 75,
        "title": "Seven Pocket Women Bag",
        "description": "Seven Pocket Women Bag Handbags Lady Shoulder Crossbody Bag Female Purse Seven Pocket Bag",
        "prevPrice": 1170,
        "price": 888,
        "discountPercentage": 14.87,
        "review": 6587,
        "rating": 4.93,
        "stock": 13,
        "brand": "Steal Frame",
        "category": "bags",
        "thumbnail": "https://i.dummyjson.com/data/products/75/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/75/1.jpg",
            "https://i.dummyjson.com/data/products/75/2.jpg",
            "https://i.dummyjson.com/data/products/75/3.jpg",
            "https://i.dummyjson.com/data/products/75/thumbnail.jpg"
        ]
    },
    {
        "id": 76,
        "title": "Silver Ring Set Women",
        "description": "Jewelry Type:RingsCertificate Type:NonePlating:Silver PlatedShapeattern:noneStyle:CLASSICReligious",
        "prevPrice": 870,
        "price": 665,
        "discountPercentage": 13.57,
        "review": 9487,
        "rating": 4.61,
        "stock": 51,
        "brand": "Darojay",
        "category": "bags",
        "thumbnail": "https://i.dummyjson.com/data/products/76/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/76/1.jpg",
            "https://i.dummyjson.com/data/products/76/2.jpg",
            "https://i.dummyjson.com/data/products/76/thumbnail.jpg"
        ]
    },
    {
        "id": 77,
        "title": "Rose Ring",
        "description": "Brand: The Greetings Flower Colour: RedRing Colour: GoldenSize: Adjustable",
        "prevPrice": 1170,
        "price": 876,
        "discountPercentage": 3.22,
        "review": 1487,
        "rating": 4.2,
        "stock": 149,
        "brand": "Copenhagen Luxe",
        "category": "bags",
        "thumbnail": "https://i.dummyjson.com/data/products/77/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/77/1.jpg",
            "https://i.dummyjson.com/data/products/77/2.jpg",
            "https://i.dummyjson.com/data/products/77/3.jpg",
            "https://i.dummyjson.com/data/products/77/thumbnail.jpg"
        ]
    },
    {
        "id": 78,
        "title": "Rhinestone Korean Style Open Rings",
        "description": "Fashion Jewellery 3Pcs Adjustable Pearl Rhinestone Korean Style Open Rings For Women",
        "prevPrice": 777,
        "price": 655,
        "discountPercentage": 8.02,
        "review": 487,
        "rating": 4.9,
        "stock": 9,
        "brand": "Fashion Jewellery",
        "category": "bags",
        "thumbnail": "https://i.dummyjson.com/data/products/78/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/78/thumbnail.jpg"
        ]
    },
    {
        "id": 79,
        "title": "Elegant Female Pearl Earrings",
        "description": "Elegant Female Pearl Earrings Set Zircon Pearl Earings Women Party Accessories 9 Pairs/Set",
        "prevPrice": 765,
        "price": 234,
        "discountPercentage": 12.8,
        "rating": 4.4,
        "review": 5464,
        "stock": 16,
        "brand": "Fashion Jewellery",
        "category": "bags",
        "thumbnail": "https://i.dummyjson.com/data/products/79/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/79/1.jpg"
        ]
    },
    {
        "id": 80,
        "title": "Chain Pin Tassel Earrings",
        "description": "Pair Of Ear Cuff Butterfly Long Chain Pin Tassel Earrings - Silver ( Long Life Quality Product)",
        "prevPrice": 1070,
        "price": 987,
        "discountPercentage": 17.75,
        "review": 53297,
        "rating": 4.5,
        "stock": 9,
        "brand": "Cuff Butterfly",
        "category": "bags",
        "thumbnail": "https://i.dummyjson.com/data/products/80/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/80/1.jpg",
            "https://i.dummyjson.com/data/products/80/2.jpg",
            "https://i.dummyjson.com/data/products/80/3.png",
            "https://i.dummyjson.com/data/products/80/4.jpg",
            "https://i.dummyjson.com/data/products/80/thumbnail.jpg"
        ]
    },
    {
        "id": 81,
        "title": "Round Silver Frame Sun Glasses",
        "description": "A pair of sunglasses can protect your eyes from being hurt. For car driving, vacation travel, outdoor activities, social gatherings,",
        "prevPrice": 899,
        "price": 776,
        "discountPercentage": 10.1,
        "review": 8654,
        "rating": 4.94,
        "stock": 78,
        "brand": "Designer Sun Glasses",
        "category": "electronics",
        "thumbnail": "https://i.dummyjson.com/data/products/81/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/81/1.jpg",
            "https://i.dummyjson.com/data/products/81/2.jpg",
            "https://i.dummyjson.com/data/products/81/3.jpg",
            "https://i.dummyjson.com/data/products/81/4.webp",
            "https://i.dummyjson.com/data/products/81/thumbnail.jpg"
        ]
    },
    {
        "id": 82,
        "title": "Kabir Singh Square Sunglass",
        "description": "Orignal Metal Kabir Singh design 2020 Sunglasses Men Brand Designer Sun Glasses Kabir Singh Square Sunglass",
        "prevPrice": 999,
        "price": 566,
        "discountPercentage": 15.6,
        "review": 3465,
        "rating": 4.2,
        "stock": 78,
        "brand": "Designer Sun Glasses",
        "category": "electronics",
        "thumbnail": "https://i.dummyjson.com/data/products/82/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/82/1.jpg",
            "https://i.dummyjson.com/data/products/82/2.webp",
            "https://i.dummyjson.com/data/products/82/3.jpg",
            "https://i.dummyjson.com/data/products/82/4.jpg",
            "https://i.dummyjson.com/data/products/82/thumbnail.jpg"
        ]
    },
    {
        "id": 83,
        "title": "Wiley X Night Vision Yellow Glasses",
        "description": "Wiley X Night Vision Yellow Glasses for Riders - Night Vision Anti Fog Driving Glasses - Free Night Glass Cover - Shield Eyes From Dust and Virus- For Night Sport Matches",
        "prevPrice": 1111,
        "price": 934,
        "discountPercentage": 6.33,
        "review": 2345,
        "rating": 4.7,
        "stock": 115,
        "brand": "mastar watch",
        "category": "electronics",
        "thumbnail": "https://i.dummyjson.com/data/products/83/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/83/1.jpg",
            "https://i.dummyjson.com/data/products/83/2.jpg",
            "https://i.dummyjson.com/data/products/83/3.jpg",
            "https://i.dummyjson.com/data/products/83/4.jpg",
            "https://i.dummyjson.com/data/products/83/thumbnail.jpg"
        ]
    },
    {
        "id": 84,
        "title": "Square Sunglasses",
        "description": "Fashion Oversized Square Sunglasses Retro Gradient Big Frame Sunglasses For Women One Piece Gafas Shade Mirror Clear Lens 17059",
        "prevPrice": 879,
        "price": 786,
        "discountPercentage": 13.89,
        "review": 9443,
        "rating": 4.4,
        "stock": 64,
        "brand": "mastar watch",
        "category": "electronics",
        "thumbnail": "https://i.dummyjson.com/data/products/84/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/84/1.jpg",
            "https://i.dummyjson.com/data/products/84/2.jpg",
            "https://i.dummyjson.com/data/products/84/thumbnail.jpg"
        ]
    },
    {
        "id": 85,
        "title": "LouisWill Men Sunglasses",
        "description": "LouisWill Men Sunglasses Polarized Sunglasses UV400 Sunglasses Day Night Dual Use Safety Driving Night Vision Eyewear AL-MG Frame Sun Glasses with Free Box for Drivers",
        "prevPrice": 1219,
        "price": 987,
        "discountPercentage": 11.27,
        "review": 653,
        "rating": 4.3,
        "stock": 92,
        "brand": "LouisWill",
        "category": "electronics",
        "thumbnail": "https://i.dummyjson.com/data/products/85/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/85/1.jpg",
            "https://i.dummyjson.com/data/products/85/2.jpg",
            "https://i.dummyjson.com/data/products/85/thumbnail.jpg"
        ]
    },
    {
        "id": 86,
        "title": "Bluetooth Aux",
        "description": "Bluetooth Aux Bluetooth Car Aux Car Bluetooth Transmitter Aux Audio Receiver Handfree Car Bluetooth Music Receiver Universal 3.5mm Streaming A2DP Wireless Auto AUX Audio Adapter With Mic For Phone MP3",
        "prevPrice": 1270,
        "price": 876,
        "discountPercentage": 10.56,
        "review": 9678,
        "rating": 4.57,
        "stock": 22,
        "brand": "Car Aux",
        "category": "electronics",
        "thumbnail": "https://i.dummyjson.com/data/products/86/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/86/1.jpg",
            "https://i.dummyjson.com/data/products/86/2.webp",
            "https://i.dummyjson.com/data/products/86/3.jpg",
            "https://i.dummyjson.com/data/products/86/4.jpg",
            "https://i.dummyjson.com/data/products/86/thumbnail.jpg"
        ]
    },
    {
        "id": 87,
        "title": "t Temperature Controller Incubator Controller",
        "description": "Both Heat and Cool Purpose, Temperature control range; -50 to +110, Temperature measurement accuracy; 0.1, Control accuracy; 0.1",
        "prevPrice": 770,
        "price": 567,
        "discountPercentage": 11.3,
        "review": 4332,
        "rating": 3.7,
        "stock": 37,
        "brand": "W1209 DC12V",
        "category": "electronics",
        "thumbnail": "https://i.dummyjson.com/data/products/87/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/87/1.jpg",
            "https://i.dummyjson.com/data/products/87/2.jpg",
            "https://i.dummyjson.com/data/products/87/3.jpg",
            "https://i.dummyjson.com/data/products/87/4.jpg",
            "https://i.dummyjson.com/data/products/87/thumbnail.jpg"
        ]
    },
    {
        "id": 88,
        "title": "TC Reusable Silicone Magic Washing Gloves",
        "description": "TC Reusable Silicone Magic Washing Gloves with Scrubber, Cleaning Brush Scrubber Gloves Heat Resistant Pair for Cleaning of Kitchen, Dishes, Vegetables and Fruits, Bathroom, Car Wash, Pet Care and Multipurpose",
        "prevPrice": 1290,
        "price": 998,
        "discountPercentage": 3.19,
        "review": 54245,
        "rating": 4.98,
        "stock": 42,
        "brand": "TC Reusable",
        "category": "electronics",
        "thumbnail": "https://i.dummyjson.com/data/products/88/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/88/1.jpg",
            "https://i.dummyjson.com/data/products/88/2.jpg",
            "https://i.dummyjson.com/data/products/88/3.jpg",
            "https://i.dummyjson.com/data/products/88/4.webp",
            "https://i.dummyjson.com/data/products/88/thumbnail.jpg"
        ]
    },
    {
        "id": 89,
        "title": "Qualcomm original Car Charger",
        "description": "best Quality CHarger , Highly Recommended to all best Quality CHarger , Highly Recommended to all",
        "prevPrice": 770,
        "price": 554,
        "discountPercentage": 17.53,
        "review": 123452,
        "rating": 4.2,
        "stock": 79,
        "brand": "TC Reusable",
        "category": "electronics",
        "thumbnail": "https://i.dummyjson.com/data/products/89/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/89/1.jpg",
            "https://i.dummyjson.com/data/products/89/2.jpg",
            "https://i.dummyjson.com/data/products/89/3.jpg",
            "https://i.dummyjson.com/data/products/89/4.jpg",
            "https://i.dummyjson.com/data/products/89/thumbnail.jpg"
        ]
    },
    {
        "id": 90,
        "title": "Cycle Bike Glow",
        "description": "Universal fitment and easy to install no special wires, can be easily installed and removed. Fits most standard tyre air stem valves of road, mountain bicycles, motocycles and cars.Bright led will turn on w",
        "prevPrice": 999,
        "price": 876,
        "discountPercentage": 11.08,
        "review": 6524,
        "rating": 4.1,
        "stock": 63,
        "brand": "Neon LED Light",
        "category": "electronics",
        "thumbnail": "https://i.dummyjson.com/data/products/90/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/90/1.jpg",
            "https://i.dummyjson.com/data/products/90/2.jpg",
            "https://i.dummyjson.com/data/products/90/3.jpg",
            "https://i.dummyjson.com/data/products/90/4.jpg",
            "https://i.dummyjson.com/data/products/90/thumbnail.jpg"
        ]
    },
    {
        "id": 91,
        "title": "Black Motorbike",
        "description": "Engine Type:Wet sump, Single Cylinder, Four Stroke, Two Valves, Air Cooled with SOHC (Single Over Head Cam) Chain Drive Bore & Stroke:47.0 x 49.5 MM",
        "prevPrice": 1080,
        "price": 988,
        "discountPercentage": 13.63,
        "review": 764457,
        "rating": 4.04,
        "stock": 115,
        "brand": "METRO 70cc Motorcycle - MR70",
        "category": "motorcycle",
        "thumbnail": "https://i.dummyjson.com/data/products/91/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/91/1.jpg",
            "https://i.dummyjson.com/data/products/91/2.jpg",
            "https://i.dummyjson.com/data/products/91/3.jpg",
            "https://i.dummyjson.com/data/products/91/4.jpg",
            "https://i.dummyjson.com/data/products/91/thumbnail.jpg"
        ]
    },
    {
        "id": 92,
        "title": "HOT SALE IN EUROPE electric racing motorcycle",
        "description": "HOT SALE IN EUROPE electric racing motorcycle electric motorcycle for sale adult electric motorcycles",
        "prevPrice": 1070,
        "price": 920,
        "discountPercentage": 14.4,
        "review": 9679,
        "rating": 4.19,
        "stock": 22,
        "brand": "BRAVE BULL",
        "category": "motorcycle",
        "thumbnail": "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/92/1.jpg",
            "https://i.dummyjson.com/data/products/92/2.jpg",
            "https://i.dummyjson.com/data/products/92/3.jpg",
            "https://i.dummyjson.com/data/products/92/4.jpg"
        ]
    },
    {
        "id": 93,
        "title": "Automatic Motor Gas Motorcycles",
        "description": "150cc 4-Stroke Motorcycle Automatic Motor Gas Motorcycles Scooter motorcycles 150cc scooter",
        "prevPrice": 1190,
        "price": 1050,
        "discountPercentage": 3.34,
        "review": 6422,
        "rating": 4.84,
        "stock": 127,
        "brand": "shock absorber",
        "category": "motorcycle",
        "thumbnail": "https://i.dummyjson.com/data/products/93/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/93/1.jpg",
            "https://i.dummyjson.com/data/products/93/2.jpg",
            "https://i.dummyjson.com/data/products/93/3.jpg",
            "https://i.dummyjson.com/data/products/93/4.jpg",
            "https://i.dummyjson.com/data/products/93/thumbnail.jpg"
        ]
    },
    {
        "id": 94,
        "title": "new arrivals Fashion motocross goggles",
        "description": "new arrivals Fashion motocross goggles motorcycle motocross racing motorcycle",
        "prevPrice": 1210,
        "price": 900,
        "discountPercentage": 3.85,
        "review": 4545,
        "rating": 4.06,
        "stock": 109,
        "brand": "JIEPOLLY",
        "category": "motorcycle",
        "thumbnail": "https://i.dummyjson.com/data/products/94/thumbnail.webp",
        "images": [
            "https://i.dummyjson.com/data/products/94/1.webp",
            "https://i.dummyjson.com/data/products/94/2.jpg",
            "https://i.dummyjson.com/data/products/94/3.jpg",
            "https://i.dummyjson.com/data/products/94/thumbnail.webp"
        ]
    },
    {
        "id": 95,
        "title": "Wholesale cargo lashing Belt",
        "description": "Wholesale cargo lashing Belt Tie Down end Ratchet strap customized strap 25mm motorcycle 1500kgs with rubber handle",
        "prevPrice": 1170,
        "price": 930,
        "discountPercentage": 17.67,
        "review": 8887,
        "rating": 4.21,
        "stock": 144,
        "brand": "Xiangle",
        "category": "motorcycle",
        "thumbnail": "https://i.dummyjson.com/data/products/95/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/95/1.jpg",
            "https://i.dummyjson.com/data/products/95/2.jpg",
            "https://i.dummyjson.com/data/products/95/3.jpg",
            "https://i.dummyjson.com/data/products/95/4.jpg",
            "https://i.dummyjson.com/data/products/95/thumbnail.jpg"
        ]
    },
    {
        "id": 96,
        "title": "lighting ceiling kitchen",
        "description": "Wholesale slim hanging decorative kid room lighting ceiling kitchen chandeliers pendant light modern",
        "prevPrice": 970,
        "price": 787,
        "discountPercentage": 14.89,
        "review": 657,
        "rating": 4.83,
        "stock": 96,
        "brand": "lightingbrilliance",
        "category": "lighting",
        "thumbnail": "https://i.dummyjson.com/data/products/96/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/96/1.jpg",
            "https://i.dummyjson.com/data/products/96/2.jpg",
            "https://i.dummyjson.com/data/products/96/3.jpg",
            "https://i.dummyjson.com/data/products/96/4.jpg",
            "https://i.dummyjson.com/data/products/96/thumbnail.jpg"
        ]
    },
    {
        "id": 97,
        "title": "Metal Ceramic Flower",
        "description": "Metal Ceramic Flower Chandelier Home Lighting American Vintage Hanging Lighting Pendant Lamp",
        "prevPrice": 770,
        "price": 665,
        "discountPercentage": 10.94,
        "review": 1211,
        "rating": 4.93,
        "stock": 146,
        "brand": "Ifei Home",
        "category": "lighting",
        "thumbnail": "https://i.dummyjson.com/data/products/97/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/97/1.jpg",
            "https://i.dummyjson.com/data/products/97/2.jpg",
            "https://i.dummyjson.com/data/products/97/3.jpg",
            "https://i.dummyjson.com/data/products/97/4.webp",
            "https://i.dummyjson.com/data/products/97/thumbnail.jpg"
        ]
    },
    {
        "id": 98,
        "title": "3 lights lndenpant kitchen islang",
        "description": "3 lights lndenpant kitchen islang dining room pendant rice paper chandelier contemporary led pendant light modern chandelier",
        "prevPrice": 1070,
        "price": 987,
        "discountPercentage": 5.92,
        "review": 12198,
        "rating": 4.99,
        "stock": 44,
        "brand": "DADAWU",
        "category": "lighting",
        "thumbnail": "https://i.dummyjson.com/data/products/98/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/98/1.jpg",
            "https://i.dummyjson.com/data/products/98/2.jpg",
            "https://i.dummyjson.com/data/products/98/3.jpg",
            "https://i.dummyjson.com/data/products/98/4.jpg",
            "https://i.dummyjson.com/data/products/98/thumbnail.jpg"
        ]
    },
    {
        "id": 99,
        "title": "American Vintage Wood Pendant Light",
        "description": "American Vintage Wood Pendant Light Farmhouse Antique Hanging Lamp Lampara Colgante",
        "prevPrice": 670,
        "price": 556,
        "discountPercentage": 8.84,
        "review": 5657,
        "rating": 4.32,
        "stock": 138,
        "brand": "Ifei Home",
        "category": "lighting",
        "thumbnail": "https://i.dummyjson.com/data/products/99/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/99/1.jpg",
            "https://i.dummyjson.com/data/products/99/2.jpg",
            "https://i.dummyjson.com/data/products/99/3.jpg",
            "https://i.dummyjson.com/data/products/99/4.jpg",
            "https://i.dummyjson.com/data/products/99/thumbnail.jpg"
        ]
    },
    {
        "id": 100,
        "title": "Crystal chandelier maria theresa for 12 light",
        "description": "Crystal chandelier maria theresa for 12 light",
        "prevPrice": 1270,
        "price": 876,
        "discountPercentage": 16,
        "review": 7787,
        "rating": 4.74,
        "stock": 133,
        "brand": "YIOSI",
        "category": "lighting",
        "thumbnail": "https://i.dummyjson.com/data/products/100/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/100/1.jpg",
            "https://i.dummyjson.com/data/products/100/2.jpg",
            "https://i.dummyjson.com/data/products/100/3.jpg",
            "https://i.dummyjson.com/data/products/100/thumbnail.jpg"
        ]
    }

];

export default ProductData;